### ISSUE TITLE
Add all the numbers from an array, with max depth of 1.

### ISSUE THREAD

**Issue by Satyakoidala** [Satyakoidala/Programming_solved#1]
## Sample
Input - `[1, 2, 3, [4, 5]]`
Output - `1 + 2 + 3 + 4 + 5 = 15` 

## Language restrictions
JavaScript only

**Comment by Sanjaykumar-IT** [comment]
Please assign this to me

**Comment by Satyakoidala** [comment]
@Sanjaykumar-IT assigned!

**Comment by Sanjaykumar-IT** [comment]
Hi @Satyakoidala , Created PR https://github.com/Satyakoidala/programming-solved/pull/10 
Can you pls review it?

**Comment by Satyakoidala** [comment]
PR merged! Thank you!
