### ISSUE TITLE
Multiply two given numbers without using addition operator

### ISSUE THREAD

**Issue by Satyakoidala** [Satyakoidala/Programming_solved#2]
## Sample
Input - `2, 3`
Output - 6

## Language restrictions
Any language

**Comment by Sanjaykumar-IT** [comment]
Please assign this to me

**Comment by Satyakoidala** [comment]
> Please assign this to me

Done!

**Comment by Sanjaykumar-IT** [comment]
Hi @Satyakoidala  Created PR: https://github.com/Satyakoidala/programming-solved/pull/9
Please review it

**Comment by Satyakoidala** [comment]
@Sanjaykumar-IT , good work!
