### ISSUE TITLE
Given a number, return true if it is a numeric palindrome or else false

### ISSUE THREAD

**Issue by Satyakoidala** [Satyakoidala/Programming_solved#3]
## Sample
Input - `121`
Output - `false` 

## Language restrictions
any language

**Comment by SumitMangrati** [comment]
new to open source , assign me this task ill get it done

**Comment by Sanjaykumar-IT** [comment]
Please assign this to me

**Comment by Satyakoidala** [comment]
> Please assign this to me

done!

**Comment by Sanjaykumar-IT** [comment]
Hi @Satyakoidala , Created PR https://github.com/Satyakoidala/programming-solved/pull/7 
Please check

**Comment by Satyakoidala** [comment]
> Hi @Satyakoidala , Created PR #7 Please check

https://github.com/Satyakoidala/programming-solved/pull/7 --> Good job!
