### ISSUE TITLE
Given a number, find the sum of its digits

### ISSUE THREAD

**Issue by Satyakoidala** [Satyakoidala/Programming_solved#4]
## Sample
Input - `123`
Output - `6` 

## Language restrictions
Any language

**Comment by SumitMangrati** [comment]
could you please assign me this task

**Comment by Sanjaykumar-IT** [comment]
Please assign this task to me

**Comment by Satyakoidala** [comment]
> Please assign this task to me

Assigned!

**Comment by Sanjaykumar-IT** [comment]
Hi @Satyakoidala , created PR https://github.com/Satyakoidala/programming-solved/pull/6  please review it?

**Comment by Satyakoidala** [comment]
Good work!
